### ISSUE TITLE
Cannot connect to PG DB

### ISSUE THREAD

**Issue by abadrinath947** [cvickery/dgw_processor#1]
Hi, thanks for this library!

I'm having issues installing and connecting to the PG database that you reference in these files:

``` bash
[abadrinath@... dgw_processor]$ grep -ri 'from pgconnection' *
course_contexts.py:from pgconnection import PgConnection
development/tests/test_dgw_parser.py:from pgconnection import PgConnection
development/test_contexts/contexts.py:from pgconnection import PgConnection
dgw_driver.py:from pgconnection import PgConnection
dgw_parser.py:from pgconnection import PgConnection
dgw_utils.py:from pgconnection import PgConnection
extract_block.py:from pgconnection import PgConnection
htmlificization.py:from pgconnection import PgConnection
only_one_course.py:from pgconnection import PgConnection
testing/generate_test_data.py:from pgconnection import PgConnection
```

The only package named `pgconnection` that I was able to find was https://pypi.org/project/django-pgconnection/, which does not contain any class named `PgConnection`. I wasn't able to find any file that contains this class in this package either, so I'm not sure where to find this. I'm able to download the scribe code from this link: https://transfer-app.qc.cuny.edu/requirements/, and I've verified that ANTLR works as expected, but this seems to be an issue that's preventing me from using the package.

I'm unable to generate test data and try to test the package either, so if you had any ideas to solve this, that would be great! 

Let me know if I'm missing anything, but I've read through the README in the project folder and testing folder, as well as visited the various links and have found no information about this.

**Comment by cvickery** [comment]
Hi, hope I can help!

The issue is that this project and my [transfer-app](https://github.com/cvickery/transfer-app) project work together, and the pgconnection module is part of that project. One option would be for you to extract pgconnection.py from that project and put it where this project can find it.

In my machines I have:
`$ echo $PYTHONPATH
/Users/vickery/Projects/dgw_processor:/Users/vickery/Projects/transfer_app/
`

But the issue is a bit deeper than that. This project depends on several CUNY Curriculum tables, which are built by the transfer-app project, using extracts from CUNY's PeopleSoft system. So the feature of the parser where it looks up all the courses, colleges, etc. isn't going to work for you without those tables.

Feel free to contact me directly by email (cvickery@qc.cuny.edu) if you want to discuss strategies for your work further.
